version: '3'

services: 
    web:
        build: ./web
        container_name: ewb_monitoring_web
        restart: unless-stopped
        ports: 
            - 8081:3000
        environment: 
            - MONGODB=db:27017
    db:
        image: mongo:4.1.8-xenial
        container_name: ewb_monitoring_db
        restart: unless-stopped
        volumes:
            - dbdata:/data/db

volumes:
    dbdata: